plugin: netbox.netbox.nb_inventory
api_endpoint: http://ct2.lan.com:8000
validate_certs: false
config_context: true
interfaces: true
prefixes: true
services: true
group_by:
  - device_roles
  - sites
  - device_types
ansible_python_interpreter=/root/net3/venv/bin/python3
